Repository jemmia-diamond/fn, pull requests merged in 2025-08, with the labels that each got.

#86 Feature: sync erp data (User, Employee, Sales Person) to db
  package.json
  prisma/schema.prisma
  prisma/schema/erpnext.prisma
  prisma/schema/schema.prisma
  src/services/erp/core/user/user.js
  src/services/erp/index.js
  src/services/erp/selling/index.js
  src/services/erp/selling/sales-person/sales-person.js
  src/services/erp/setup/employee/employee.js
  src/services/erp/setup/index.js
  src/services/schedule-handler.js
Labels: Review effort 4/5, Review effort 3/5, Possible security concern

#92 feat: add redirects feature
  src/controllers/redirect-controller.js
  src/index.js
  src/routes/app.js
  src/routes/index.js
Labels: Review effort 2/5

#36 Feature/serial number to ERP
  src/services/erp/selling/index.js
  src/services/erp/selling/serial/serial.js
  src/services/schedule-handler.js
Labels: Review effort 2/5, Possible security concern

#91 feature: sync lark base table record
  prisma/schema/larksuite.prisma
  prisma/schema/migrations/20250808062818_00002/migration.sql
  prisma/schema/schema.prisma
  src/services/larksuite/docs/base/index.js
  src/services/larksuite/docs/base/record/record.js
  src/services/larksuite/docs/constant.js
  src/services/larksuite/docs/index.js
  src/services/larksuite/index.js
  src/services/larksuite/lark.js
  src/services/schedule-handler.js
Labels: Review effort 3/5, Possible security concern

#93 Setup husky pre-commit lint hook
  .husky/pre-commit
  README.md
  eslint.config.mjs
  package.json
  pnpm-lock.yaml
Labels: Review effort 2/5

#96 feat: add public router and public API to get product by ID
  src/controllers/ecommerce/index.js
  src/controllers/ecommerce/product-controller.js
  src/index.js
  src/routes/index.js
  src/routes/public-api.js
  src/services/ecommerce/product/product.js
Labels: Review effort 2/5, Possible security concern

#102 Feature/sync lead child tables
  prisma/schema/erpnext.prisma
  prisma/schema/migrations/20250812074408_00003/migration.sql
  src/services/erp/crm/index.js
  src/services/erp/crm/lead_budget/lead_budget.js
  src/services/erp/crm/lead_demand/lead_demand.js
  src/services/erp/crm/province/province.js
  src/services/erp/crm/region/region.js
  src/services/schedule-handler.js
  wrangler.jsonc
Labels: Review effort 2/5

#98 feat: add API for getting, resetting and updating order stats from KV
  src/controllers/ecommerce/ind-day-stat-controller.js
  src/controllers/ecommerce/index.js
  src/controllers/webhook/haravan/erp/order.js
  src/routes/api.js
  src/services/ecommerce/enum.js
  src/services/ecommerce/index.js
  src/services/ecommerce/order/ind-day-stat.js
  src/services/queue-handler.js
Labels: Review effort 2/5

#105 enhance: handle exception when dequeue order events
  src/services/erp/selling/sales-order/sales-order.js
Labels: Review effort 2/5

#109 refactor: replace product controller by jewelry controller
  src/controllers/ecommerce/index.js
  src/controllers/ecommerce/product-controller.js
  src/routes/api.js
  src/routes/public-api.js
  src/services/ecommerce/product/product.js
Labels: Review effort 2/5

#111 fix: move delete ind stats route from public to private
  .dev.vars.example
  src/routes/api.js
  src/routes/public-api.js
  src/services/ecommerce/order/ind-day-stat.js
Labels: Review effort 2/5

#90 get overall info of order tracking
  src/controllers/ecommerce/index.js
  src/controllers/ecommerce/order-tracking-controller.js
  src/routes/api.js
  src/services/ecommerce/index.js
  src/services/ecommerce/order-tracking/order-tracking.js
  src/services/ecommerce/order-tracking/queries/get-latest-orderid.js
  src/services/ecommerce/order-tracking/queries/get-order-overall-info.js
  src/services/ecommerce/order-tracking/utils/format-order-tracking.js
Labels: Review effort 3/5

#112 Feature/nhattin service
  src/controllers/delivery/delivery-tracking-controller.js
  src/controllers/delivery/index.js
  src/routes/api.js
  src/routes/public-api.js
  src/services/ecommerce/order-tracking/order-tracking.js
  src/services/nhattin/index.js
  src/services/nhattin/nhattin-client.js
  wrangler.jsonc
Labels: Review effort 2/5, Possible security concern

#114 update wrangler
  wrangler.jsonc
Labels: Review effort 2/5

#116 Feature/zalo/send message
  src/services/ecommerce/zalo-message/enums/zalo-template.enum.js
  src/services/ecommerce/zalo-message/utils/format-template-zalo.js
  src/services/zalo-message/zalo-message.js
Labels: Review effort 2/5

#117 fix: fix cloudflare dequeue issues and update ind stats config
  src/services/ecommerce/order/ind-day-stat.js
Labels: Review effort 2/5

#118 fix: remove the count_order key and fix the cloudflare dequeue issues
  src/services/ecommerce/order/ind-day-stat.js
Labels: Review effort 2/5

#125 Fix: use haravan token secret key
  src/services/ecommerce/order-tracking/order-tracking.js
Labels: Review effort 2/5

#119 Sync Serial Number to ERP more frequently
  src/services/erp/selling/serial/serial.js
  src/services/schedule-handler.js
Labels: Review effort 2/5

#126 add name
  src/services/ecommerce/zalo-message/utils/format-template-zalo.js
Labels: Review effort 1/5

#128 fix the zalo send
  src/controllers/webhook/haravan/erp/order.js
  src/services/ecommerce/enum.js
  src/services/ecommerce/zalo-message/enums/zalo-template.enum.js
  src/services/ecommerce/zalo-message/utils/format-template-zalo.js
  src/services/ecommerce/zalo-message/zalo-message.js
  src/services/queue-handler.js
Labels: Review effort 2/5

#132 try fixing 403 error updating records on lark (production only)
  src/services/larksuite/docs/base/record/record.js
  src/services/product_quote/order/order.js
Labels: Review effort 2/5

#131 add more fields to api tracking
  src/services/ecommerce/order-tracking/enums/order-delivery-status.enum.js
  src/services/ecommerce/order-tracking/order-tracking.js
  src/services/ecommerce/order-tracking/queries/get-order-overall-info.js
  src/services/ecommerce/order-tracking/utils/format-order-tracking.js
Labels: Review effort 3/5

#135 enhance: request Larksuite users with pagination
  src/services/larksuite/contact/user/user.js
Labels: Review effort 2/5
