Repository jemmia-diamond/fn, pull requests merged in 2025-07, with the labels that each got.

#43 Feature/pancake conversation assignment
  src/controllers/webhook/frappe/pancake/conversation-assignment.js
Labels: Review effort 1/5

#45 feature: add custom logs to queue handler
  src/services/queue-handler.js
Labels: Review effort 1/5

#38 Feature re-assign leads in off hours
  src/frappe/frappe-client.js
  src/services/erp/automation/assigment-rule/assigment-rule.js
  src/services/schedule-handler.js
Labels: Review effort 2/5

#47 ignore event type which is not messaging
  src/controllers/webhook/pancake/erp/message.js
Labels: Review effort 1/5

#48 Feature/website lead to ERP
  src/services/erp/contacts/contact/contact.js
  src/services/erp/crm/lead/lead.js
Labels: Review effort 2/5

#55 Bug Fix: Secret store for Call Log Service
  src/services/env-handler.js
  src/services/erp/telephony/call-log/call-log.js
Labels: Review effort 2/5

#58 Enhance: assign to default user if no user found
  src/services/erp/automation/assigment-rule/assigment-rule.js
Labels: Review effort 2/5

#56 Feature: Sync Lead From Call Logs
  src/services/erp/contacts/contact/contact.js
  src/services/erp/crm/lead/lead.js
  src/services/schedule-handler.js
  src/stringee/utils/phone-number.js
Labels: Review effort 2/5, Possible security concern

#60 Feature: Jewelry collection api for Ecommerce
  src/controllers/ecommerce/index.js
  src/controllers/ecommerce/product-controller.js
  src/index.js
  src/routes/ecommerce.js
  src/routes/index.js
  src/services/ecommerce/index.js
  src/services/ecommerce/product/product.js
  src/services/ecommerce/product/utils/jewelry.js
Labels: Review effort 3/5, Possible security concern

#62 Feature: Jewelry Product Search
  src/controllers/ecommerce/index.js
  src/controllers/ecommerce/search-controller.js
  src/routes/ecommerce.js
  src/services/ecommerce/product/product.js
Labels: Review effort 3/5, Possible security concern

#61 Feature: Sync Leave Approval To Database
  src/services/larksuite/approval/constant.js
  src/services/larksuite/approval/index.js
  src/services/larksuite/approval/instance/instance.js
  src/services/larksuite/approval/instance/utils/formTransformation.js
  src/services/larksuite/index.js
  src/services/larksuite/lark.js
  src/services/schedule-handler.js
Labels: Review effort 3/5

#64 fix: use subquery to avoid duplicates variants
  src/services/ecommerce/product/product.js
Labels: Review effort 3/5

#65 feat: add more note for lead
  src/services/erp/crm/lead/lead.js
Labels: Review effort 1/5

#66 Feature: return more men wedding rings for ecom
  src/services/ecommerce/product/utils/jewelry.js
Labels: Review effort 2/5

#68 Feature/ Add KV Cloudflare
  wrangler.jsonc
Labels: Review effort 1/5

#69 Fix: Rename order service
  src/controllers/erp/order-controller.js
  src/services/erp/selling/index.js
  src/services/erp/selling/sales-order/sales-order.js
  src/services/queue-handler.js
Labels: Review effort 2/5

#74 Feature: CORS for Ecommerce API
  src/index.js
Labels: Review effort 3/5, Possible security concern

#76 enhance: add pages to query params
  src/controllers/ecommerce/product-controller.js
Labels: Review effort 2/5

#77 Enhance: handle duplicate variants and filters on fineness and price
  src/controllers/ecommerce/product-controller.js
  src/services/ecommerce/product/product.js
  src/services/ecommerce/product/utils/jewelry.js
Labels: Review effort 3/5

#81 Modify README.md
  README.md
Labels: Review effort 1/5

#83 FEATURE/ implement GET wedding ring endpoint
  src/controllers/ecommerce/index.js
  src/controllers/ecommerce/wedding-ring-controller.js
  src/routes/api.js
  src/services/ecommerce/product/product.js
  src/services/ecommerce/product/utils/wedding-ring.js
Labels: Review effort 3/5, Possible security concern

#84 feature: add DiamondController and endpoint for diamond profile image…
  src/controllers/ecommerce/diamond-controller.js
  src/controllers/ecommerce/index.js
  src/routes/api.js
  src/services/ecommerce/product/product.js
Labels: Review effort 2/5, Possible security concern
