Repository jemmia-diamond/fn, pull requests merged in 2025-09, with the labels that each got.

#183 fix(tracking): fix temp change prisma to neon
  src/services/ecommerce/order-tracking/order-tracking.js
  src/services/ecommerce/zalo-message/zalo-message.js
Labels: Review effort 2/5

#185 feat(selling module): Sync Promotion, Purpose, Category tables from ERPNext
  prisma/schema/erpnext.prisma
  prisma/schema/migrations/20250905042621_add_promotion_purpose_category_tables/migration.sql
  src/services/erp/selling/index.js
  src/services/erp/selling/product-category/product-category.js
  src/services/erp/selling/promotion/promotion.js
  src/services/erp/selling/purchase_purpose/purchase_purpose.js
  src/services/schedule-handler.js
Labels: Review effort 2/5

#184 feat(erp-sales-order): add carrier_status field
  src/services/erp/selling/sales-order/sales-order.js
Labels: Review effort 2/5

#188 fix(sales-order): wrong carrier field name
  src/services/erp/selling/sales-order/sales-order.js
Labels: Review effort 2/5

#186 feat(sales-order-notification): more message content and validation
  src/services/erp/selling/sales-order/sales-order.js
  src/services/erp/selling/sales-order/utils/sales-order-notification.js
  src/services/haravan/products/product-variant/constant.js
  src/services/larksuite/group-chat/group-management/constant.js
Labels: Review effort 3/5

#190 Fix/validate integer orderid
  src/controllers/ecommerce/order-tracking-controller.js
  src/services/utils/num-helper.js
Labels: Review effort 2/5

#191 chore(erp): fix log
  src/services/erp/crm/lead/lead.js
Labels: Review effort 1/5, Possible security concern

#193 fix(erp-sales-order): wrong attribute path for carrier status
  src/services/erp/selling/sales-order/sales-order.js
Labels: Review effort 2/5

#194 refactor(jewelry-api): migrate to material view
  src/services/ecommerce/product/utils/jewelry.js
Labels: Review effort 2/5

#196 fix(erp-lead-api): fix sql syntax
  src/services/erp/crm/lead/lead.js
Labels: Review effort 1/5, Possible security concern

#195 Feat(database): Add function to refresh materialized view
  src/services/db-operations/index.js
  src/services/db-operations/materialized-view/materialized-view.js
  src/services/schedule-handler.js
Labels: Review effort 2/5, Possible security concern

#203 chore(sales-order-notification): more message content and validation
  src/services/erp/selling/sales-order/sales-order.js
  src/services/erp/selling/sales-order/utils/sales-order-notification.js
Labels: Review effort 2/5

#207 feat(wedding-rings-api): add fineness and material_colors metadata
  src/services/ecommerce/product/product.js
  src/services/ecommerce/product/utils/wedding-ring.js
Labels: Review effort 2/5
